In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.linear_model  import LogisticRegression
from sklearn.feature_selection import RFE
from sklearn.metrics import confusion_matrix
from sklearn.impute import KNNImputer
import statsmodels.api as sm

In [2]:
#所有Header
Header=["age", "bp", "sg", "al", "su", "rbc", "pc", "pcc", "ba", "bgr",
        "bu", "sc", "sod", "pot", "hemo", "pcv", "wc", "rc", "htn", "dm",
        "cad", "appet", "pe", "ane", "class"]

#資料屬於category data的 Header
Header_cat=["sg", "al", "su", "rbc", "pc", "pcc", "ba", "htn", "dm","cad", "appet", "pe", "ane", "class"] 

df = pd.read_excel ('MDS_Assignment1_kidney.xlsx',header=None,names=Header)

In [3]:
df

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,48,80,1.02,1,0,?,normal,notpresent,notpresent,121,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7,50,1.02,4,0,?,normal,notpresent,notpresent,?,...,38,6000,?,no,no,no,good,no,no,ckd
2,62,80,1.01,2,3,normal,normal,notpresent,notpresent,423,...,31,7500,?,no,yes,no,poor,no,yes,ckd
3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51,80,1.01,2,0,normal,normal,notpresent,notpresent,106,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,55,80,1.02,0,0,normal,normal,notpresent,notpresent,140,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,42,70,1.025,0,0,normal,normal,notpresent,notpresent,75,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,12,80,1.02,0,0,normal,normal,notpresent,notpresent,100,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,17,60,1.025,0,0,normal,normal,notpresent,notpresent,114,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,58,80,1.025,0,0,normal,normal,notpresent,notpresent,131,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [4]:
for i in range(0,len(df)):
    if df['class'][i]!= 'ckd' and df['class'][i]!= 'notckd':
        df.drop([i],inplace=True)
df = df.reset_index(drop=True)

In [5]:
df

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,class
0,48,80,1.02,1,0,?,normal,notpresent,notpresent,121,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7,50,1.02,4,0,?,normal,notpresent,notpresent,?,...,38,6000,?,no,no,no,good,no,no,ckd
2,62,80,1.01,2,3,normal,normal,notpresent,notpresent,423,...,31,7500,?,no,yes,no,poor,no,yes,ckd
3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51,80,1.01,2,0,normal,normal,notpresent,notpresent,106,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,55,80,1.02,0,0,normal,normal,notpresent,notpresent,140,...,47,6700,4.9,no,no,no,good,no,no,notckd
383,42,70,1.025,0,0,normal,normal,notpresent,notpresent,75,...,54,7800,6.2,no,no,no,good,no,no,notckd
384,12,80,1.02,0,0,normal,normal,notpresent,notpresent,100,...,49,6600,5.4,no,no,no,good,no,no,notckd
385,17,60,1.025,0,0,normal,normal,notpresent,notpresent,114,...,51,7200,5.9,no,no,no,good,no,no,notckd
386,58,80,1.025,0,0,normal,normal,notpresent,notpresent,131,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [6]:
df_des = df.replace({'?':None})
des=df_des.describe()

In [7]:
des

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc
count,378.000000,378.000000,342.000000,343.000000,341.000000,345.000000,369.000000,371.000000,306.000000,305.000000,339.000000,321.000000,288.000000,264.000000
mean,51.455026,76.269841,1.017573,0.988338,0.463343,148.275362,57.331165,3.093127,137.586601,4.632459,12.546608,38.903427,8415.277778,4.698106
std,16.963351,13.649698,0.005676,1.339845,1.112485,80.038451,50.898689,5.819282,10.480733,3.228669,2.935955,9.069524,2947.775857,1.012787
min,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,3.100000,9.000000,2200.000000,2.100000
25%,42.000000,70.000000,1.015000,0.000000,0.000000,100.000000,27.000000,0.900000,135.000000,3.800000,10.350000,32.000000,6500.000000,3.900000
50%,54.000000,80.000000,1.020000,0.000000,0.000000,121.000000,41.000000,1.200000,138.000000,4.400000,12.700000,40.000000,8000.000000,4.800000
75%,64.000000,80.000000,1.020000,2.000000,0.000000,163.000000,66.000000,2.800000,142.000000,4.900000,15.000000,45.000000,9800.000000,5.400000
max,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,17.800000,54.000000,26400.000000,6.500000

In [8]:
# # of missing value by counting null
count_missing = df_des.isnull().sum(axis=0)
des= des.append(pd.Series(count_missing, name='# of missing value'))

# # of outlier by value out of (Q1 - 1.5 * IQR, Q3 + 1.5 * IQR)
Q1 = df_des.quantile(0.25)
Q3 = df_des.quantile(0.75)
IQR = Q3 - Q1
count_outlier = ((df_des < (Q1 - 1.5 * IQR)) | (df_des > (Q3 + 1.5 * IQR))).sum()
des= des.append(pd.Series(count_outlier, name='# of outlier'))

In [9]:
des

,age,bp,sg,al,su,bgr,bu,sc,sod,pot,...,appet,ba,cad,class,dm,htn,pc,pcc,pe,rbc
count,378.000000,378.000000,342.000000,343.000000,341.000000,345.000000,369.000000,371.000000,306.000000,305.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,51.455026,76.269841,1.017573,0.988338,0.463343,148.275362,57.331165,3.093127,137.586601,4.632459,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,16.963351,13.649698,0.005676,1.339845,1.112485,80.038451,50.898689,5.819282,10.480733,3.228669,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2.000000,50.000000,1.005000,0.000000,0.000000,22.000000,1.500000,0.400000,4.500000,2.500000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,42.000000,70.000000,1.015000,0.000000,0.000000,100.000000,27.000000,0.900000,135.000000,3.800000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,54.000000,80.000000,1.020000,0.000000,0.000000,121.000000,41.000000,1.200000,138.000000,4.400000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,64.000000,80.000000,1.020000,2.000000,0.000000,163.000000,66.000000,2.800000,142.000000,4.900000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,90.000000,180.000000,1.025000,5.000000,5.000000,490.000000,391.000000,76.000000,163.000000,47.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
# of missing value,9.000000,9.000000,45.000000,44.000000,46.000000,42.000000,18.000000,16.000000,81.000000,82.000000,...,1.0,4.0,2.0,0.0,2.0,2.0,62.0,4.0,1.0,143.0
# of outlier,8.000000,34.000000,6.000000,0.000000,61.000000,34.000000,36.000000,50.000000,15.000000,4.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df = df.replace({'ckd':1, 'notckd':0})

y = df[Header[-1]]
X = pd.DataFrame(df[Header[0:-1]], columns = df[Header[0:-1]].columns)

In [11]:
imp = SimpleImputer(missing_values = '?' , strategy = 'most_frequent')
X2 = pd.DataFrame( imp.fit_transform(X[Header_cat[:-1]]), 
                  columns = X[Header_cat[:-1]].columns)

for i in range(len(Header_cat)-1):
    X[Header_cat[i]] = X2[Header_cat[i]]

In [13]:
X = pd.get_dummies(X, columns = Header_cat[:-1])

In [14]:
X = X.replace({'?': None})

imputer = KNNImputer(n_neighbors=10, weights="uniform")
X2 = imputer.fit_transform(X)
X = pd.DataFrame(X2, columns = X.columns)

In [15]:
pd.DataFrame(X)

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,...,dm_no,dm_yes,cad_no,cad_yes,appet_good,appet_poor,pe_no,pe_yes,ane_no,ane_yes
0,48.0,80.0,121.0,36.0,1.2,139.3,4.19,15.4,44.0,7800.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
1,7.0,50.0,118.6,18.0,0.8,136.2,3.98,11.3,38.0,6000.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
2,62.0,80.0,423.0,53.0,1.8,134.7,4.37,9.6,31.0,7500.0,...,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
3,48.0,70.0,117.0,56.0,3.8,111.0,2.50,11.2,32.0,6700.0,...,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,51.0,80.0,106.0,26.0,1.4,139.3,4.05,11.6,35.0,7300.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,55.0,80.0,140.0,49.0,0.5,150.0,4.90,15.7,47.0,6700.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
383,42.0,70.0,75.0,31.0,1.2,141.0,3.50,16.5,54.0,7800.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
384,12.0,80.0,100.0,26.0,0.6,137.0,4.40,15.8,49.0,6600.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
385,17.0,60.0,114.0,50.0,1.0,135.0,4.90,14.2,51.0,7200.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
386,58.0,80.0,131.0,18.0,1.1,141.0,3.50,15.8,53.0,6800.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=random.randint(0, 1000))

In [21]:
logreg = LogisticRegression(max_iter=10000)
rfe = RFE(logreg, 15)
rfe = rfe.fit(X_train, y_train.values.ravel())

par=[]
for i in range(len(rfe.ranking_)):
    if rfe.ranking_[i]==1:
        par.append(X.columns[i])

C:\Users\elena\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass n_features_to_select=15 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "

In [118]:
print(par)

['sc', 'hemo', 'rc', 'sg_1.01', 'sg_1.015', 'sg_1.02', 'sg_1.025', 'al_0', 'su_0', 'htn_no', 'dm_no', 'dm_yes', 'appet_poor', 'pe_no', 'pe_yes']

In [22]:
print(par)

['sc', 'hemo', 'rc', 'sg_1.01', 'sg_1.015', 'sg_1.02', 'sg_1.025', 'al_0', 'su_0', 'htn_yes', 'dm_no', 'dm_yes', 'appet_good', 'appet_poor', 'pe_yes']

In [23]:
logreg = LogisticRegression()
logreg.fit(X_train[par], y_train)

LogisticRegression()

In [24]:
y_pred = logreg.predict(X_test[par])
print('Accuracy rate: {:.2f}'.format(logreg.score(X_test[par], y_test)))

Accuracy rate: 0.99

In [25]:
con = confusion_matrix(y_test, y_pred)
print(con)

[[26  0]
 [ 1 51]]