In [1]:
import pandas as pd
import numpy as np

In [146]:
df_pred = pd.read_csv("Q_pred50.csv")
df_B = pd.read_csv("B.csv")

/Users/wuyunwei/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3418: DtypeWarning: Columns (21) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [159]:
df_p = df_pred[(df_pred["CreationDate"]<'2021-01-01') & (df_pred["CreationDate"]>'2020-01-01')]
df_p.reset_index(drop = True, inplace = True)
df_p

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,Title,Tags,AnswerCount,CommentCount,FavoriteCount,ClosedDate,CommunityOwnedDate,ContentLicense,Time_AA,TBAA_RL_Pred
0,59549258,1,59549692.0,NaN,2020-01-01 00:14:31,NaN,-1,48,<p>My bot is not working as planned.<br>\nFor ...,11032283.0,...,My Discord XP bot isn't recognizing user data ...,<python><discord><discord.py>,1,2,1.0,NaN,NaN,CC BY-SA 4.0,8828.0,6
1,59549310,1,NaN,NaN,2020-01-01 00:33:01,NaN,-2,1910,<pre><code>pi@raspberrypi:~/examples/lite/exam...,8706702.0,...,raspberry pi 4 tensorflow installation,<python><tensorflow><raspberry-pi><hdfs>,2,4,1.0,NaN,NaN,CC BY-SA 4.0,NaN,37
2,59549322,1,NaN,NaN,2020-01-01 00:35:38,NaN,11,3319,<p>Trying to import pytest on Python 3.8 fails...,1893164.0,...,"Importing Pytest fails with ""AttributeError: '...",<python><pytest>,1,0,NaN,NaN,NaN,CC BY-SA 4.0,NaN,22
3,59549341,1,59549351.0,NaN,2020-01-01 00:39:41,NaN,0,20,<p>Suppose I have the dataframe</p>\n\n<pre><c...,10852841.0,...,Converting timedeltas to integers for consecut...,<python-3.x><pandas>,1,0,NaN,NaN,NaN,CC BY-SA 4.0,233.0,15
4,59549374,1,59549386.0,NaN,2020-01-01 00:52:07,NaN,0,77,<p>How to append an array with a dictionary in...,1285061.0,...,python append an array with a dictionary insid...,<python><arrays><dictionary>,1,4,NaN,NaN,NaN,CC BY-SA 4.0,288.0,33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162486,65526307,1,NaN,NaN,2020-12-31 23:40:16,NaN,0,293,<p>I have a classification problem with class ...,13038520.0,...,"issue with high recall, low precision after ov...",<python><machine-learning><scikit-learn><overs...,0,2,NaN,NaN,NaN,CC BY-SA 4.0,NaN,19
162487,65526315,1,65526406.0,NaN,2020-12-31 23:43:05,NaN,0,181,<h2><strong>Question:</strong></h2>\n<p>If you...,11772533.0,...,Python: counting number of iterations to achie...,<python><function><loops><while-loop>,3,2,NaN,NaN,NaN,CC BY-SA 4.0,1190.0,33
162488,65526338,1,NaN,NaN,2020-12-31 23:49:53,NaN,3,1482,<p>I feel stupid but I cannot seem to fix this...,9899725.0,...,Why am I getting this matplotlib error for plo...,<python><matplotlib>,0,9,NaN,NaN,NaN,CC BY-SA 4.0,NaN,23
162489,65526356,1,NaN,NaN,2020-12-31 23:54:26,NaN,1,238,<p>I've created the following graph:</p>\n<pre...,309706.0,...,"Pyspark + Graphframes: ""recursive"" message agg...",<python><apache-spark><pyspark><apache-spark-s...,1,1,1.0,NaN,NaN,CC BY-SA 4.0,NaN,28
162490,65526360,1,NaN,NaN,2020-12-31 23:55:16,NaN,0,29,<p>I am trying to print all screen_names found...,NaN,...,Using twython to log all screen_names of users...,<python><twitter><twython>,0,5,NaN,NaN,NaN,CC BY-SA 4.0,NaN,6

In [162]:
df_p ["Qrecord"] = ""
df_p ["Arecord"] = ""
df_p ["Urecord"] = ""
df_p ["Arate"] = ""
df_p ["Pyrecord"] = ""
df_p ["Pyrate"] = ""

<ipython-input-162-9f657a1d5a44>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Qrecord"] = ""
<ipython-input-162-9f657a1d5a44>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Arecord"] = ""
<ipython-input-162-9f657a1d5a44>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Urecord"] = ""
<ipython-input-162-9f657a1d5a44>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Arate"] = ""
<ipython-input-162-9f657a1d5a44>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Pyrecord"] = ""
<ipython-input-162-9f657a1d5a44>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Pyrate"] = ""

In [163]:
for i in range(len(df_p)):
    
    id = df_p["Id"][i]
    df_temp = df_B[df_B["Id"]==id]

    if str(df_p["AcceptedAnswerId"][i]) == 'nan':
        A, U = 0, 1
    else:
        A, U = 1, 0
        
    if not df_temp.empty:
        A += len(df_temp[df_temp["AcceptedAnswerId"].notnull()])
        U += len(df_temp[df_temp["AcceptedAnswerId"].isnull()])
    
    py = 1
    for j in df_temp.index:
        if 'python' in df_B["tags"][j]:
            py += 1
        
    df_p ["Qrecord"][i] = len(df_temp)+1
    df_p ["Arecord"][i] = A
    df_p ["Urecord"][i] = U
    df_p ["Arate"][i] = A/(A+U)
    df_p ["Pyrecord"][i] = py
    df_p ["Pyrate"][i] = py/(len(df_temp)+1)

<ipython-input-163-ab12bfaf3da5>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Qrecord"][i] = len(df_temp)+1
<ipython-input-163-ab12bfaf3da5>:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Arecord"][i] = A
<ipython-input-163-ab12bfaf3da5>:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Urecord"][i] = U
<ipython-input-163-ab12bfaf3da5>:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Arate"][i] = A/(A+U)
<ipython-input-163-ab12bfaf3da5>:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Pyrecord"][i] = py
<ipython-input-163-ab12bfaf3da5>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p ["Pyrate"][i] = py/(len(df_temp)+1)

In [164]:
df_p

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,CommunityOwnedDate,ContentLicense,Time_AA,TBAA_RL_Pred,Qrecord,Arecord,Urecord,Arate,Pyrate,Pyrecord
0,59549258,1,59549692.0,NaN,2020-01-01 00:14:31,NaN,-1,48,<p>My bot is not working as planned.<br>\nFor ...,11032283.0,...,NaN,CC BY-SA 4.0,8828.0,6,5,4,1,0.8,1.0,5
1,59549310,1,NaN,NaN,2020-01-01 00:33:01,NaN,-2,1910,<pre><code>pi@raspberrypi:~/examples/lite/exam...,8706702.0,...,NaN,CC BY-SA 4.0,NaN,37,1,0,1,0.0,1.0,1
2,59549322,1,NaN,NaN,2020-01-01 00:35:38,NaN,11,3319,<p>Trying to import pytest on Python 3.8 fails...,1893164.0,...,NaN,CC BY-SA 4.0,NaN,22,13,7,6,0.538462,0.923077,12
3,59549341,1,59549351.0,NaN,2020-01-01 00:39:41,NaN,0,20,<p>Suppose I have the dataframe</p>\n\n<pre><c...,10852841.0,...,NaN,CC BY-SA 4.0,233.0,15,11,8,3,0.727273,1.0,11
4,59549374,1,59549386.0,NaN,2020-01-01 00:52:07,NaN,0,77,<p>How to append an array with a dictionary in...,1285061.0,...,NaN,CC BY-SA 4.0,288.0,33,22,13,9,0.590909,0.818182,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162486,65526307,1,NaN,NaN,2020-12-31 23:40:16,NaN,0,293,<p>I have a classification problem with class ...,13038520.0,...,NaN,CC BY-SA 4.0,NaN,19,15,5,10,0.333333,1.0,15
162487,65526315,1,65526406.0,NaN,2020-12-31 23:43:05,NaN,0,181,<h2><strong>Question:</strong></h2>\n<p>If you...,11772533.0,...,NaN,CC BY-SA 4.0,1190.0,33,9,7,2,0.777778,0.111111,1
162488,65526338,1,NaN,NaN,2020-12-31 23:49:53,NaN,3,1482,<p>I feel stupid but I cannot seem to fix this...,9899725.0,...,NaN,CC BY-SA 4.0,NaN,23,1,0,1,0.0,1.0,1
162489,65526356,1,NaN,NaN,2020-12-31 23:54:26,NaN,1,238,<p>I've created the following graph:</p>\n<pre...,309706.0,...,NaN,CC BY-SA 4.0,NaN,28,5,3,2,0.6,0.4,2
162490,65526360,1,NaN,NaN,2020-12-31 23:55:16,NaN,0,29,<p>I am trying to print all screen_names found...,NaN,...,NaN,CC BY-SA 4.0,NaN,6,1,0,1,0.0,1.0,1

In [165]:
df_p["Accepted"] = ""
for i in range(len(df_p)):
    if str(df_p["AcceptedAnswerId"][i]) == 'nan':
        df_p["Accepted"][i] =0
    else:
        df_p["Accepted"][i] =1

<ipython-input-165-d6654ff07cc7>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p["Accepted"] = ""
<ipython-input-165-d6654ff07cc7>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p["Accepted"][i] =1
<ipython-input-165-d6654ff07cc7>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_p["Accepted"][i] =0

In [166]:
df_p

,Id,PostTypeId,AcceptedAnswerId,ParentId,CreationDate,DeletionDate,Score,ViewCount,Body,OwnerUserId,...,ContentLicense,Time_AA,TBAA_RL_Pred,Qrecord,Arecord,Urecord,Arate,Pyrate,Pyrecord,Accepted
0,59549258,1,59549692.0,NaN,2020-01-01 00:14:31,NaN,-1,48,<p>My bot is not working as planned.<br>\nFor ...,11032283.0,...,CC BY-SA 4.0,8828.0,6,5,4,1,0.8,1.0,5,1
1,59549310,1,NaN,NaN,2020-01-01 00:33:01,NaN,-2,1910,<pre><code>pi@raspberrypi:~/examples/lite/exam...,8706702.0,...,CC BY-SA 4.0,NaN,37,1,0,1,0.0,1.0,1,0
2,59549322,1,NaN,NaN,2020-01-01 00:35:38,NaN,11,3319,<p>Trying to import pytest on Python 3.8 fails...,1893164.0,...,CC BY-SA 4.0,NaN,22,13,7,6,0.538462,0.923077,12,0
3,59549341,1,59549351.0,NaN,2020-01-01 00:39:41,NaN,0,20,<p>Suppose I have the dataframe</p>\n\n<pre><c...,10852841.0,...,CC BY-SA 4.0,233.0,15,11,8,3,0.727273,1.0,11,1
4,59549374,1,59549386.0,NaN,2020-01-01 00:52:07,NaN,0,77,<p>How to append an array with a dictionary in...,1285061.0,...,CC BY-SA 4.0,288.0,33,22,13,9,0.590909,0.818182,18,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162486,65526307,1,NaN,NaN,2020-12-31 23:40:16,NaN,0,293,<p>I have a classification problem with class ...,13038520.0,...,CC BY-SA 4.0,NaN,19,15,5,10,0.333333,1.0,15,0
162487,65526315,1,65526406.0,NaN,2020-12-31 23:43:05,NaN,0,181,<h2><strong>Question:</strong></h2>\n<p>If you...,11772533.0,...,CC BY-SA 4.0,1190.0,33,9,7,2,0.777778,0.111111,1,1
162488,65526338,1,NaN,NaN,2020-12-31 23:49:53,NaN,3,1482,<p>I feel stupid but I cannot seem to fix this...,9899725.0,...,CC BY-SA 4.0,NaN,23,1,0,1,0.0,1.0,1,0
162489,65526356,1,NaN,NaN,2020-12-31 23:54:26,NaN,1,238,<p>I've created the following graph:</p>\n<pre...,309706.0,...,CC BY-SA 4.0,NaN,28,5,3,2,0.6,0.4,2,0
162490,65526360,1,NaN,NaN,2020-12-31 23:55:16,NaN,0,29,<p>I am trying to print all screen_names found...,NaN,...,CC BY-SA 4.0,NaN,6,1,0,1,0.0,1.0,1,0

In [157]:
datelist = pd.date_range(start="2020-01-01",end="2020-12-31").tolist()
datelist = [d.strftime("%Y-%m-%d") for d in datelist]
QD = df_B["CreationDate"].tolist()
QD = [d[:10] for d in QD]
for d in datelist:
    if d not in QD:
        print(d)

In [158]:
df_p.to_csv('Q_50+B.csv', index = False)